BEGIN;
ALTER TYPE "permission_action" ADD VALUE IF NOT EXISTS 'case.filing.submit';
ALTER TYPE "case_stage" ADD VALUE IF NOT EXISTS 'WAITING_FORMAL_ACCEPTANCE';
ALTER TYPE "material_category" ADD VALUE IF NOT EXISTS 'FILING_EVIDENCE';
ALTER TYPE "material_category" ADD VALUE IF NOT EXISTS 'FILING_SCREENSHOT';
COMMIT;
