BEGIN;
ALTER TYPE "permission_action" ADD VALUE IF NOT EXISTS 'case.acceptance.register';
ALTER TYPE "case_stage" ADD VALUE IF NOT EXISTS 'WAITING_HEARING';
ALTER TYPE "material_category" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_NOTICE';
ALTER TYPE "material_category" ADD VALUE IF NOT EXISTS 'PAYMENT_LIST';
ALTER TYPE "material_category" ADD VALUE IF NOT EXISTS 'SERVICE_DOCUMENT';
COMMIT;
