export function verifyCaseHearingDatabase(): Promise<{
  initialVersion: number;
  lawyerScheduled: boolean;
  replaySame: boolean;
  revokedReplayDenied: boolean;
  rollbackSaveClean: boolean;
  beforeDue: number;
  failedAdvanceCount: number;
  rollbackAdvanceClean: boolean;
  startupAdvanced: number;
  secondStartupAdvanced: number;
  firstAdvanceCount: number;
  firstSystemAuditCount: number;
  firstSystemActorNull: boolean;
  rollbackCorrectionClean: boolean;
  overdueStage: string;
  overdueAdvanceSame: boolean;
  futureStage: string;
  futureAdvanceNull: boolean;
  secondAdvanced: number;
  finalAdvanceCount: number;
  finalSystemAuditCount: number;
  historyArrangementCount: number;
  correctionCount: number;
  immutableArrangement: string | null;
  immutableAdvance: string | null;
  immutableAudit: string | null;
  earlyDateSQL: string | null;
  mismatchAuditSQL: string | null;
  duplicateAdvance: string | null;
}>;
